### PR TITLE
RealInternalStore refactoring

### PR DESCRIPTION
**Pull request by fabioCollini**
I have tried to implement the proposal I did last week, this PR is the final result. There are a lot of things to fix, I have opened this PR to discuss and to understand if it's a good way to implement it. This is the final result, a Store can be defined in this way:

```
val store: Store<String, Int> = Store<Int, Int> { it + Random.nextInt() }
                .addParser { it.toString() }
                .addPersister(persister)
                .addCache()
                .addInflight()
```

This PR splits `RealInternalStore` into multiple classes defined in this [package](https://github.com/fabioCollini/Core/tree/feature/wrappers/store/src/main/java/com/nytimes/android/external/store3/base/wrappers). In this way the order is defined by the user, for example a parser can be added before or after the persister and everything is optional.

A builder is not necessary anymore but I am not sure this is a good idea because the `add` methods are available also after the construction. However I think it's not complicated to reintroduce a builder again (or something else more idiomatic in Kotlin).

### CODE REVIEW

**Comment by fabioCollini** [comment]
> This is great. Only thing I can think of is guidance for where to do in flight. Currently in flight is always between persister and fetcher. Wondering what behavior changes from it being somewhere else.

Using this structure the inflight can be added everywhere, I am not sure what's the best configuration. I added a TODO to decide if the inflight should contain two caches (one for `get` and another for `fresh`). Using a single cache a `get` call can wait for a `fresh` invocation even if the cached data is valid.

**Comment by fabioCollini** [comment]
@digitalbuddha do you remember why the persister always returns the read data (even right after writing a new data)? Right now we have:

```
val newValue = wrappedStore.get(key)
persister.write(key, newValue)
return persister.read(key)!!
```

but it could be just:

```
val newValue = wrappedStore.get(key)
persister.write(key, newValue)
return newValue
```

In this way it would be faster because it returns the new data without an extra read

**Comment by digitalbuddha** [comment]
Yes but not unidirectional anymore. I want to make sure hat gets written to disk will not fail and I we before filling memory cache. Otherwise we cache bad data

**Comment by fabioCollini** [comment]
> Yes but not unidirectional anymore. I want to make sure what gets written to disk will not fail and we before filling memory cache. Otherwise we cache bad data

You are right! Let me add a comment in the class

**Comment by fabioCollini** [comment]
I thought about this problem:

> Using this structure the inflight can be added everywhere, I am not sure what's the best configuration. I added a TODO to decide if the inflight should contain two caches (one for `get` and another for `fresh`). Using a single cache a `get` call can wait for a `fresh` invocation even if the cached data is valid.

Adding an inflight before the persister there are other problems: for example in case a `get` with stale data is invoked while a `fetch` is running. The `get` on the inflight will call the `get` on the persister that will call the `fetch` on the fetcher ignoring the other inflight call.

I think we can solve in two ways:
 * the inflight is allowed only right before the fetcher (maybe with a boolean to avoid using it)
 * a `isStale(key)` method is added to the `Store` class so we can decide to execute a `fetch` instead of a `get` a the beginning of call and not at persister/cache level

The first solution is easier, the second is more complicated but maybe could be useful for other features as well.

**Comment by digitalbuddha** [comment]
Agreed, I like the first one, inflight is an attribute of a fetcher. That is keeping it sismple

**Comment by fabioCollini** [comment]
Ok! Is a boolean enough to enable/disable inflight or do you think that a `MemoryPolicy` is needed? It seems that a request is removed from the cache at the end, on Store3 there is `.doAfterTerminate(() -> inFlightRequests.invalidate(key))`. So the expiration configuration created in `CacheFactory.createBaseInFlighter` seems to be ignored (maybe is used if the fetcher is really slow and the cache expire before the end, but I am not sure that this is a useful feature)

**Pull request merged**
